<?php

namespace CHC\WarManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VillageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillageRepository extends EntityRepository
{
}
